# Generated by Django 4.1.7 on 2023-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(default=None, upload_to='StockImages', verbose_name='Imagem do produto'),
        ),
    ]
