# Generated by Django 4.1.7 on 2023-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_stock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='CeleryTasks')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
